
% FSE/RARE image, as well as the assumed number of Otsu intensity ranges,
% and an initial choice of which class indices to include as the
% hemorrhage segmentation.

% For each dataset, record the following as an individual cell element in the 
% the file_info array (using the example as a guide):

% <basename for output file and GUI labeling>,
% <location of the nrrd files for the current subject>,
% <name of the FSE nrrd file>,
% <number of Otsu thresholds>,
% <vector of indices that are considered as segmenting the cord
% <name of isotropic denoised MEDIC images>,
% <name of isotropic SWI image>,
% <name of cord mask, resampled on isotropic SWI image>,
% <number of Otsu thresholds on SWI to segment the cord>,
% <classmap indices on SWI to consider initially as hemhorrhage>,


proc_basepath = 'C:\Users\user\MRI\Hemorrhage Study\Input NRRD files';
info_filepath = [proc_basepath filesep 'Otsu_hem_fileinfo.mat'];

file_info = {
    {'Neptunite_E',...
        'Neptunite/Neptunite_E_d01',...
        'Neptunite_E_d01_exp4_P1_ax_FSE_denoised.nrrd',...
        3,[1 2],...
        'Neptunite_E_d01_exp7_P1_isotropic_MEDIC_denoised.nrrd',...
        'Neptunite_E_d01_isotropic_SWI_E7P1.nrrd',...
        'Neptunite_E_RARE_cordmask_for_SWI.nrrd',...        
        4,[2 3]},...
    {'Elbaite_E',...
        'Elbaite/Elbaite_E_ip1',...
        'Elbaite_E_ip1_exp6_P1_ax_FSE_denoised',...
        3,[1 2],...
        'Elbaite_E_ip1_exp9_P1_isotropic_MEDIC_denoised.nrrd',...
        'Elbaite_E_ip1_isotropic_SWI_E9P1.nrrd',...     
        'Elbaite_E_RARE_cordmask_for_SWI.nrrd',...        
        4,[2 3]},...
   }

save(info_filepath,'file_info','input_basepath')